### ISSUE TITLE
Tokens for deployer and committer users

### ISSUE THREAD

**Issue by alsotop** [REBELinBLUE/deployer#123]
Another couple of tokens that might be useful for commands would be the current deployer and committer. Not wanting to make too many tokens and make it messy, but perhaps {{ deployer_email }} {{ deployer_name }} {{ committer_email }} and {{ committer_name }}.

Example use case: we're using Rollbar, and we can notify Rollbar of a deploy being made by posting a webhook, and you can optionally provide the user who made the deploy.

**Comment by REBELinBLUE** [comment]
👍 Makes sense, I am away until next week so don't have a chance to do it but I will look early next week

**Comment by REBELinBLUE** [comment]
If a deployment is triggered via a webhook it is possible for the ``{{ deployer_name }}`` and ``{{ deployer_email }}`` to not have values.

What would you expect to happen in that case, blank values? The webhook can specify a name, so I guess ``{{ deployer_name }}`` would be the value specified via the hook otherwise ``webhook`` but not sure about email

**Comment by alsotop** [comment]
Hmm, that's a good point. Well I suppose either it should fall back to blank values, or we could instead replace with a token that represents a "deploy source" (or something worded better) - and then either that is "webhook" or the username?

**Comment by REBELinBLUE** [comment]
Fixed in https://github.com/REBELinBLUE/deployer/commit/e8c7a6af9937bfd9052b7cf13eef517b7329e569
