### ISSUE TITLE
0.0.25 breaks on composer install

### ISSUE THREAD

**Issue by alsotop** [REBELinBLUE/deployer#147]
Updating to 0.0.25 breaks on composer install, with the following error:

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

[RuntimeException]
Error Output: PHP Fatal error:  Class 'REBELinBLUE\Deployer\Providers\JwtServiceProvider' not found in /var/www/deploy.hightechclick.com/bootstrap/cache/compiled.php on line 6923

**Comment by REBELinBLUE** [comment]
Can you try the following `rm bootstrap/cache/*` first?

**Comment by javiyt** [comment]
Same here

**Comment by REBELinBLUE** [comment]
Yeah from some searching it seems to be a common problem in Laravel if you remove a service provider because it is referenced compiled.php so artisan can't remove it because it then has an error. The fix is to remove it manually from bootstrap/cache/ and then run composer install again.

I'll see if I can get composer to remove it before updating, but then that means it will be compiled on each new update which probably isn't much of an issue really

**Comment by REBELinBLUE** [comment]
https://github.com/laravel/framework/issues/9660 yeah that is the issue
