### ISSUE TITLE
nasty bug

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#171]
Hey,
i found a nasty bug today

i have 2 serves for deployment then i disabled a server, now when i hit deploy.... for custom commands, its trying to run on both servers.

![x](http://www.clipular.com/c/6643475886374912.png?k=nmeZmMo0Apqv0xpYN8F3_NCPtzU)

**Comment by REBELinBLUE** [comment]
When you say you disabled the server what do you mean? Did you delete it?

The `Deploy code?` option on a server doesn't disable it, it is specifically so that commands can be run on a server without having to deploy the code to it, for instance if you have a server with memcache you want to restart or a load balancer which needs a command run on when a new deployment is run.

**Comment by lorvent** [comment]
no, unchecked this

![x](http://www.clipular.com/c/6113693549461504.png?k=JH2uZe8q3xXehEmgezxMx3wVRcs)

Oh....it makes sense!

**Comment by REBELinBLUE** [comment]
Another thing I need to make much clearer in the documentation ;)
