### ISSUE TITLE
Testing server. Connection Status "Testing" never ends

### ISSUE THREAD

**Issue by qunabu** [REBELinBLUE/deployer#173]
First of all - I do have **deployer** and **application** im trying to deploy on _the same machine_. What I'm trying to achive in first place is to establish connection with server. What i did 

1.   run redis with MONITOR
2.   run **deployer** with ` php artisan queue:listen redis`
3.   created new project 
4.   in project added new server 
5.   filled with credentials 
6.   `ssh_key` pasted into `authorized_keys`
6.   pressed "test server"

php cli gets `Processed: Illuminate\Broadcasting\BroadcastEvent`

redis gets 

```
1455121743.577995 [0 127.0.0.1:44908] "ZADD" "queues:default:reserved" "1455121803" "{\"job\":\"Illuminate\\\\Broadcasting\\\\BroadcastEvent\",\"data\":{\"event\":\"O:40:\\\"REBELinBLUE\\\\Deployer\\\\Events\\\\ModelChanged\\\":2:{s:5:\\\"model\\\";O:45:\\\"Illuminate\\\\Contracts\\\\Database\\\\ModelIdentifier\\\":2:{s:5:\\\"class\\\";s:27:\\\"REBELinBLUE\\\\Deployer\\\\Server\\\";s:2:\\\"id\\\";i:1;}s:10:\\\"\\u0000*\\u0000channel\\\";s:6:\\\"server\\\";}\"},\"id\":\"A2SaWMuInyTfKIFcBJBHOx8VI19n7yaL\",\"attempts\":1}"
1455121743.592391 [0 127.0.0.1:44908] "PUBLISH" "server" "{\"event\":\"REBELinBLUE\\\\Deployer\\\\Events\\\\ModelChanged\",\"data\":{\"model\":{\"id\":1,\"name\":\"XXX.XXX.XXX.XXX\",\"ip_address\":\"XXX.XXX.XXX.XXX\",\"user\":\"qunabu\",\"path\":\"\\/home\\/qunabu\\/webapps\\/solace\",\"project_id\":1,\"status\":3,\"deploy_code\":true,\"port\":22,\"order\":0}}}"
1455121743.592903 [0 127.0.0.1:44908] "ZREM" "queues:default:reserved" "{\"job\":\"Illuminate\\\\Broadcasting\\\\BroadcastEvent\",\"data\":{\"event\":\"O:40:\\\"REBELinBLUE\\\\Deployer\\\\Events\\\\ModelChanged\\\":2:{s:5:\\\"model\\\";O:45:\\\"Illuminate\\\\Contracts\\\\Database\\\\ModelIdentifier\\\":2:{s:5:\\\"class\\\";s:27:\\\"REBELinBLUE\\\\Deployer\\\\Server\\\";s:2:\\\"id\\\";i:1;}s:10:\\\"\\u0000*\\u0000channel\\\";s:6:\\\"server\\\";}\"},\"id\":\"A2SaWMuInyTfKIFcBJBHOx8VI19n7yaL\",\"attempts\":1}"

```
i've marked down IP address with XXX.XXX.XXX.XXX
and nothing else happens 
no debug information in logs 
"testing" never ends ....

**Comment by REBELinBLUE** [comment]
I haven't tried laravel with redis (I shall try it tonight) but I suspect `php artisan queue:listen redis` is just running the default queue since your log is showing the `ModelChanged` and `BroadcastEvent` jobs.

If you take a look at `examples/supervisor.conf` you will see I use a couple of queues

`deployer-high` for actual deployments, `deployer-low` for notifications and connection testing and `deployer-default` for events. (I should probably show the redis value in `config/queue.php` so that it uses `deployer-default` instead of just `default` to avoid conflicts with other apps using the queue).

So you need to tell the queue listener to use those queues otherwise it will just use the default one.

You do this with the `--queue` parameter, so for example

`php artisan queue:listen redis --queue=deployer-high,deployer-low,default`

I would recommend having at least 2 separate listeners, one for the `default` queue and one for the rest, otherwise you won't get updates to the UI until any other running jobs are done because the `Broadcast` & `ModelChanged` events won't get processed immediately.

Does that make sense?

**Comment by qunabu** [comment]
indeed it does. I'll check with those settings and let you know how it worked out.

**Comment by REBELinBLUE** [comment]
:+1:

**Comment by qunabu** [comment]
@REBELinBLUE it just worked out of the box- Thanks for that.

So server login atteption failed. 
Yet neither in `storage/logs` nor in redis Monitor there is no debug information, so I'm not sure why. fyi `APP_DEBUG=true` in `.env`

**Comment by REBELinBLUE** [comment]
I have recently changed the `TestServerConnection` stuff so it doesn't just check that it can connect to the server but also that the path specified in the server setup exists, and that it can be written to and read from so check that. I still need to update the code to display a more specific error if those fail.

Essentially all it is doing is 

```ssh -p 22 user@ip bash -s <<< 'EOF'
    cd $path
    ls $path
    touch $path/random_file_name
    mkdir $path/random_dir_name
    rm -f $path/random_file_name
    rm -rf $path/random_dir_name
EOF```

**Comment by qunabu** [comment]
I've found out that problem was with wrong permission for `authorized_keys` on my server but this was just a blind shot. Thanks for everything !!!

**Comment by REBELinBLUE** [comment]
:+1:

Awesome. I will have to put that in the documentation when I get round to finishing it
