### ISSUE TITLE
Help with dead simple setup

### ISSUE THREAD

**Issue by patrick-hertling** [REBELinBLUE/deployer#186]
Im trying to get it to work, but I'm stuck.

Im using supervisor with the example setup. The servers are running. Now I don't know what to do:

What I want: 

I have deployer installed at /var/www/deployer

I want to create the necesary configuration to connect to git@vcs.git, pull the latest version of some repo and build it to /var/www/project

Could someone make a "Hello world equivalent" for the steps to follow for the simplest deployment possible? Or just explain the steps needed. That would be awesome.

**Comment by REBELinBLUE** [comment]
Sorry, I didn't get an email notification about this message for some reason.

**Comment by REBELinBLUE** [comment]
Sorry, on my phone right now so bit tricky to type a long reply, will do it as soon as I am on a computer.

**Comment by Patabugen** [comment]
I'd also appreciate such a walk through, one thing the readme.md could do with is an explanation of how deployer does it's deploying.

My guess is: clone repo, run commands on the local server, then scp all the files to the remote server (and possibly run commands there too?

**Comment by REBELinBLUE** [comment]
I really need to finish the documentation, I am off work in a couple of weeks so hopefully will get it done then.

@patrick-hertling What you'd need to do is log in and create a project. Then navigate to the project and on the server tab add at least one server. You then need to click the "SSH key" button and add the key to the `~/.ssh/authorized_keys` on the server for the user you have set it to connect as. If you have set the project to use a git repository which needs a key (for example the ssh URL instead of the http url to a repository on github) you also need to add the key to the deploy keys for the repository. on the server tab press the test button to ensure the connection is working and if so you can then deploy.

If you have set the path on the server to `/var/www/` when you deploy you will end up with `/var/www/releases/TIMESTAMP` for each deployment. It will symlink the latest to `/var/www/latest` and that is what is changed on deployment. So you point your apache/nginx config to that folder. There can also be `/var/www/shared` if you use persistent files/configuration files as it creates the folders/files which should persist across deployments there and symlinks them.


Essentially what a deployment will do is the following

1. Clone the repository to the `storage/app/mirrors` folder on deployer, if it already exists it will instead update it
2. Run `git archive` on the repository to create a `tar.gz` of the latest revision (or the specific revision if using the rollback button)
3. rsync it to the server
4. Run the "Before create new release" commands on the server
5. Unarchive the file to /var/www/releases/timestamp
6. Run the "After create new release" commands on the server
7. Run the "Before composer install" commands on the server
8. Run composer install in the /var/www/releases/timestamp folder
9. Run the "After composer install" commands on the server
10. Run the "Before activate new release" commands on the server
11. Remove the `/var/www/latest` symlink and create the new one
12. Run the "After activate new release" commands on the server
13. Run the "Before purge old releases" commands on the server
14. Remove the oldest folders from `/var/www/releases` so that it matches the "releases to keep" setting
15. Run the "After purge old releases" commands on the server

Up to and including stage 11 if any of the commands run a non zero exit status the deployment "fails" and is rolled back. After stage 11 if that happens it "completes with errors"

**Comment by patrick-hertling** [comment]
Perfect! Thank you very much!

**Comment by REBELinBLUE** [comment]
Glad to help. I really must sort out the docs site ASAP

**Comment by Patabugen** [comment]
Is it worth just enabling the Wiki feature in GitHub and letting us help
you write the site? You can always transfer it all to a pretty site or a
CMS later.

On 9 March 2016 at 21:05, Stephen Ball <notifications@github.com> wrote:

> Glad to help. I really must sort out the docs site ASAP
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/REBELinBLUE/deployer/issues/186#issuecomment-194506291>
> .
>



-- 
Patabugen

**Comment by REBELinBLUE** [comment]
Maybe, although the docs are at https://github.com/REBELinBLUE/deployer-docs

**Comment by patrick-hertling** [comment]
If I had known about the existense of these docs,  I would have been able to continue myself :-).  Its all there. You could include a link into the README File of this repo. Thank you anyway.

**Comment by REBELinBLUE** [comment]
Yeah that aren't finished which is why they aren't linked to ;)
