### ISSUE TITLE
how to stop deployer if commits are on other branches

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#227]
Hello,

I have many branches for repo and if a user pushes to any other branch, its running deployment (on current branch only), is there anyway we can stop this?

I am using gitlab

**Comment by REBELinBLUE** [comment]
This is fixed in `master` so that Deployer will actually read the data from the request sent by Gitlab. Then in the webhook URL you'd just add a parameter `update_only=true` so it becomes `http://deployer.app/deploy/TO5pFZz8vWhDSkgiq8Kf09P5cRQqY27ELqhFqY8eXIqHWGyuMCeani2pPuJj?update_only=true`.

I am planning to tag a new release later today

**Comment by lorvent** [comment]
Wow, great to hear :tada: :tada: 

can't wait to get it.

will this apply for bitbucket/github aswell?

**Comment by REBELinBLUE** [comment]
Yeah Bitbucket, github, gitlab and beanstalkapp
