### ISSUE TITLE
update_only not working when changing branch

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#234]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [ ] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [ ] You've ran `composer install --no-dev` from the root of your installation.
- [ ] You've ran `npm install --production` from the root of your installation.
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Deployments should run for current selected branch with update_only=true
### Actual behaviour

its running deployments only on previous branch
### Steps to reproduce

1. create new project and give master branch
2. add webhook to gitlab (or any other) with update_only=true
3. make a commit to master branch, deployment will trigger
4. change branch in "Administration" to a new branch say 'xyz'
5. make a commit to 'xyz' branch, deployment is not triggering.

### Environment info
Operating System: 
PHP Version:
Node Version:
Database System:
Database Version:

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
That is not what that does. It makes it so that it only updates if the branch matches the branch currently deployed, not the branch set in the project. Because people may want to deploy a development branch by using the option on the dialog when you click "Deploy" and from that point on update only will make sure only that branch is deployed until you manually deploy a different branch

**Comment by lorvent** [comment]
I don't get you.

I have 3 branches but i want deployments only for 'xyz' branch so i set that as default branch in "administration" but its making deployments only for master branch, which i have set while creating project.

**Comment by REBELinBLUE** [comment]
I really don't know how to explain it any other way.

If you set a project to use "master" as the default branch but you then deploy "release", i.e. using this screen

![](http://dropshare.rebelinblue.com/Screen-Shot-2016-06-07-at-14.12.17/Screen-Shot-2016-06-07-at-14.12.17.png)

the `update_only` flag will ensure that anything which triggers the webhook will only deploy it it comes from the `release` branch, i.e. the latest released branch

![](http://dropshare.rebelinblue.com/Screen-Shot-2016-06-07-at-14.12.56/Screen-Shot-2016-06-07-at-14.12.56.png)

Changing the default branch for the project doesn't change this.

At work we were deploying the `master` branch, but occasionally we would have development branches which were deployed manually. If someone pushed to master we didn't want the current deployment to be changed, unless someone went in and manually deployed `master` again.

If you only ever want it to deploy a single branch, (i.e. so it can't be changed from the manual deployment screen) you need to change the default branch in the project and disable the "Allow other branches?" option, but you will need to manually deploy the new branch before the webhook is able to trigger a deployment because the current latest deploy won't be the expected branch
