### ISSUE TITLE
How to listen to push events on specific branch

### ISSUE THREAD

**Issue by obayesshelton** [REBELinBLUE/deployer#242]
Hi, 

My default branch is "develop" and I have the webhook inside GitHub on "push events" however, it runs a build every time a branch is pushed. Is there a way to only run the build job when a specific branch "develop" is pushed? 

Oliver

**Comment by REBELinBLUE** [comment]
If you click the little (?) icon by the webhook URL it should include some help. There isn't a way to limit it to specific branches as such, but there is a way to limit it so that it only deploys updates if they are to the same branch that is currently deployed. Just add `?update_only=true` to the webhook URL.

What this means is if you manually deploy the `develop` branch for instance, the webhook will only deploy `develop` until you manually deploy a different branch. 

Hope that makes sense?

**Comment by obayesshelton** [comment]
Ahhh thank, I didn't notice the little (?) icon. 

Thanks :)
