### ISSUE TITLE
Beanstalk - JOB_TOO_BIG: job data exceeds server-enforced limit

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#293]
Just a pointer for anyone using Beanstalk with this deployer and have an error of `JOB_TOO_BIG: job data exceeds server-enforced limit`. This appears in the extracting part of the deployment.

Edit `/etc/defaults/beanstalkd` and uncomment or append this to increase the bytes per job;
```
BEANSTALKD_EXTRA="-z 524280"
```

**Comment by REBELinBLUE** [comment]
Thanks, this is an issue I am aware of https://github.com/REBELinBLUE/deployer/issues/262 just have no figured out what is happening

**Comment by bbashy** [comment]
My bad. Didn't search before leaving work.

Must be the amount of data in the output from the commands it does?

**Comment by REBELinBLUE** [comment]
I think it is probably because the full log is being added to the queue each time it changes (due to the way event broadcasting works) and isn't being consumed as fast, need to figure out a way around it. I may just have to make a setting so it only updates the log every x seconds rather than realtime
